apiVersion: v1
kind: Pod
metadata:
  name: pod-near-pod-on-node01
spec:
  containers:
  - name: demoapp
    image: evgao/demoapp:v1
    ports:
    - containerPort: 80
  affinity:
    #podAntiAffinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: pod-name
              operator: In
              values:
              - pod-on-node01
          topologyKey: kubernetes.io/hostname
