apiVersion: v1
kind: Pod
metadata:
  name: pod-away-from-pod-on-node02
spec:
  containers:
  - name: demoapp
    image: evgao/demoapp:v1
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
    #podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: pod-name
            operator: In
            values:
            - pod-on-node02
        topologyKey: kubernetes.io/hostname
