kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: prom-example-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prom-example-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: http_requests
      describedObject:
        apiVersion: v1
        kind: Service
        name: prom-example-app
      target:
        type: AverageValue
        averageValue: 5
