apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-example-app
  name: prom-example-app
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: prom-example-app
