apiVersion: v1
kind: Service
metadata:
  name: demoapp-deployment-svc
  labels:
    app: demoapp-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp-deployment
