apiVersion: v1
kind: Service
metadata:
    labels:
        app: redis
    name: redis-svc-ext
spec:
#   clusterIP: None
    ports:
    - port: 6379
    selector:
        app: redis
        statefulset.kubernetes.io/pod-name: redis-0
