#apiVersion: batch/v1
apiVersion: v1
kind: Pod
metadata:
  name: cm-cmd-example
spec:
      containers:
      - name: env
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["while sleep 2; do echo Hello from ${CITY}; done"]   
        env:
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: manifest-example
              key: city
      restartPolicy: Never
