apiVersion: v1
kind: Pod
metadata:
  name: cm-env-example
spec:
      containers:
      - name: env
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["while sleep 2; do printenv CITY; done"]
        env:
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: manifest-example
              key: city
      restartPolicy: Never
