apiVersion: v1
kind: Pod
metadata:
  name: secret-test-ssh-pod
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
  containers:
  - name: ssh-test-container
    image: kroniak/ssh-client
    command: [ "/bin/sh", "-c" ]
    args:
    - | 
      mkdir -p /root/.ssh
      cp /etc/secret-volume/ssh-privatekey /root/.ssh/id_rsa
      chown 400 /root/.ssh/id_rsa
      sleep 600
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
