apiVersion: v1
kind: Pod
metadata:
  name: demoimagepullsecret-pod
spec:
  containers:
  - name: demo
    image: evgao/demo:v1
    imagePullPolicy: Always
  imagePullSecrets:
  - name: mydockeraccount
