apiVersion: v1
kind: Pod
metadata:
  name: secret-nopass-ssh
  labels:
    name: secret-test
spec:
  initContainers:
  - name: initkeys
    image: busybox
    command: [ "/bin/sh", "-c" ]
    args:
    - |
      cp /opt/ssh-publickey/authorized_keys /data/
    volumeMounts:
    - name: secret-volume
      readOnly: false
      mountPath: "/opt/ssh-publickey"
    - name: keys
      mountPath: "/data/"
  containers:
  - name: ssh-test-container
    image: panubo/sshd
    env:
    - name: SSH_ENABLE_ROOT
      value: "true"
    volumeMounts:
    - name: keys
      mountPath: "/root/.ssh/"
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-nopass
      items:
      - key: ssh-publickey
        path: authorized_keys
  - name: keys
    emptyDir: {}
