kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: myapp-pod-hpa
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: myapp_processed_ops
      target:
        type: AverageValue
        averageValue: "5"

