---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.demo.jeremyxu2010.me
  labels:
    api: foo-apiserver
    apiserver: "true"
spec:
  version: v1beta1
  group: demo.jeremyxu2010.me
  groupPriorityMinimum: 2000
  service:
    name: foo-apiserver
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRREl6T2FndVIwUEhEQU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVN3d0tnWURWUVFERENObWIyOHRZWEJwYzJWeWRtVnlMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB4T1RBM01qSXhOakEyTXpKYUZ3MHlNREEzTWpFeE5qQTJNekphTUcweEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4TERBcUJnTlZCQU1NSTJadmJ5MWhjR2x6WlhKMlpYSXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeE1ZVkp1TndYSlczL1lzN2lkL2YKWFl3ZGNET0tza0NPaFcvUlhqc0F5a3VPVzUzSlJrMTVuWUVWeW4ydFdnckloSWg4b3dIM1g3aFpWME5tS2hsVAp1VG5RVWhKWER4MVowdDRkLy81dkFCYlhkZ3pPRERGTnRaTllucS9VKy9WY1pGeEQrR0hoU0c5UUJmNkh4SWVkCnp5d0NsMVZpL3B0SVdrWitlZ2NldWRWU0xoZTZyZE1zaC9jSGFNR0Nkd0U1OWZDQ2p2NHF2aUJXSmptQ1JMY0MKR0Y5THdkODRKYmM3YXBFaFBlTWdFcFNTSCtKWExyNnp0ZWdRbGd2cVg5amFkUFUrRlNuVk9yY2V3Q0xLODVxcwpoYm5vUDZRODJPTERVb1hsa3RoYVlEeVBQT1d2d2xOWk1zRmdnS2FqaXhJWDFsR29iYThxam94b0w2ZjNvazNsCmZ3SURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCeFhRWlBEbThPZ0tTRHlnYzdaQ2UzU3RONFdDbkwKYzQza0d4NERhcTNZcG5HR21lUmpnd3pobzFKcllyTkY4RGo2M1ZJNTdLQ2I1M3JKSHFwd1UxR0VEL0w1TDNtcQpKeXE3Y2lWbnB2bHJiWWRSYXNXaHVIQzVzOUQwODdyMDBONGY4OE9YR1JHUTB0dnVEcHpUa0lFWTE4RWJuMWtBCnRHTWNMTUtuTGZyK2RyQUJPZis5S01lWGN4OFN1aldNbW4zNGFaSjNxeWRLaktseC80ajdJb1NFOG93d0pzNjcKLzlUdFBSdTRHV2l0WElvTmZtdjFSdDY3aEFIUmhlSEQ1ais0azdFMDJjbElrREIrNkNJOGluczZzZjdKRm92NgpCRUVwS0xIemUwb1ltbmo2cFRtdlZncC81THpseXc0dDkrRHVVZE1kMEN5TEVMUklKRU1oWUtuTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
