---
apiVersion: v1
kind: Service
metadata:
  name: foo-apiserver
  namespace: default
  labels:
    api: foo-apiserver
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: foo-apiserver
    apiserver: "true"
