apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: bob-csr-2
spec:
  request: $(cat ./bob.csr | base64  | tr -d '\n')
  usages: 
  - digital signature
  - key encipherment
  - client auth
  #- server auth
