apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: andy-pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: andy
