apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deployment
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      project: {{.Values.label.project}}
      app: {{.Values.label.app}}
  template:
    metadata:
      labels:
        project: {{.Values.label.project}}
        app: {{.Values.label.app}}
    spec:
      containers:
      - name: nginx
        image: {{.Values.image}}:{{.Values.imageTag}}
