apiVersion: v1
kind: ServiceAccount
metadata:
  name: clientgo-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientgo-pod-reader-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clientgo-pod-reader-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clientgo-pod-reader-clusterrole
subjects:
- kind: ServiceAccount
  name: clientgo-sa
  namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: clientgo-incluster-pod
spec:
  serviceAccountName: clientgo-sa
  containers:
  - name: goclinet
    #image: evgao/demoapp:clientgoscratch
    image: evgao/demoapp:clientgoalpine
    imagePullPolicy: IfNotPresent
  #  resources:
  #    limits:
  #      cpu: 200m
  #      memory: 200Mi
