apiVersion: v1
kind: Pod
metadata:
  name: pod-near-pod-on-mars
spec:
  containers:
  - name: demoapp
    image: evgao/demoapp:v1
    ports:
    - containerPort: 80
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: pod-name
            operator: In
            values:
            - pod-on-mars
        topologyKey: location
