apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    estado: "1"
spec:
  selector:  
    matchLabels:
      app: web
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:   # Plantilla que define los containers
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
