apiVersion: v1
kind: Pod
metadata:
  name: demoapp-preferred
spec:
  containers:
  - name: demoapp
    image: evgao/demoapp:v1
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node03
