apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylocalpvc
spec:
  storageClassName: mylocal
  #storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
