apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylocalpv
  labels:
    type: local
spec:
  storageClassName: mylocal
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mylocalpv"
