apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod-noexecute
spec:
  tolerations:
  - effect: NoExecute
    key: "key1"
    operator: "Exists"
    tolerationSeconds: 30
    #value: "vaule1"
  nodeSelector:
    kubernetes.io/hostname: node02
  containers:
  - name: test
    image: evgao/demoapp:v1
