apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-example
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #nodeSelector:
      #  nodeType: edge
      containers:
      - name: nginx
        #image: nginx:stable-alpine
        image: nginx:1.8.1
        ports:
        - containerPort: 80
