---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9898
      name: podinfo-http
      targetPort: 9898
      nodePort: 31198
      protocol: TCP
  selector:
    app: podinfo
