kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: myapp
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: myapp_processed_ops
      describedObject:
        apiVersion: v1
        kind: Service
        name: myapp
      target:
        type: AverageValue
        averageValue: "5000m"
#type: Object
#object:
#  metric:
#    name: requests-per-second
#  describedObject:
#    apiVersion: networking.k8s.io/v1beta1
#    kind: Ingress
#    name: main-route
#  target:
#    type: Value
#    value: 2k
