kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
