apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chris-pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: chris-sa
  namespace: default
- kind: User
  name: chris
  namespace: default
