apiVersion: v1
kind: Service
metadata:
  name: demo-deployment-svc
  labels:
    app: demo-deployment
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-deployment
