apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-example
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: stateful
  serviceName: app
  updateStrategy:
    type: OnDelete

# pod template
  template:
    metadata:
      labels:
        app: stateful
    spec:
      containers:
      - name: demoapp
        image: evgao/demoapp:stateful
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /data

  # pvc template
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: manual
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 1Gi
