apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: devel
namePrefix: dev-
commonLabels:
  env: devel
commonAnnotations:
  releaseDay: "on 20200624 by devel team"
patchesStrategicMerge:
- static-svc-devel.yaml
