apiVersion: v1
kind: Pod
metadata:
  name: podresource-demo-1
  namespace: demo
  labels:
    app: demoapp
spec:
  containers:
  - name: democontainer
    image: evgao/demoapp:v1
    resources:
      limits:
        memory: 2Gi
        cpu: 2
      requests:
        memory: 2Gi
        cpu: 1
