apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota
  namespace: demo
  labels:
    namespace: demo
spec:
  hard:
    requests.cpu: 2
    requests.memory: 2Gi
    limits.cpu: 2
    limits.memory: 4Gi
