apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/nfs/test-for-priority
    server: 10.0.0.2
