apiVersion: v1
kind: Pod
metadata:
  name: busybox-dynamic-pv-test
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: dynamic-pvc1
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
