kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress-controller
  template:
    metadata:
      labels:
        app: traefik-ingress-controller
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: luxas/traefik:v1.5.4
        name: traefik-ingress-controller
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
        - name: web
          containerPort: 8080
        args:
        - --configfile=/etc/traefik/traefik.toml
        volumeMounts:
        - name: traefik-cfg
          mountPath: /etc/traefik/traefik.toml
      volumes:
      - name: traefik-cfg
        configMap:
          name: traefik-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-controller
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: traefik-ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web
  labels:
    app: traefik-ingress-controller
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: traefik-ingress-controller
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ngrok-cfg
  namespace: kube-system
  labels:
    app: ngrok
data:
  ngrok.yaml: |
    web_addr: 0.0.0.0:4040
    log: stdout
    log_level: debug
    log_format: logfmt
    tunnels:
      traefik:
        proto: http
        addr: traefik-ingress-controller.kube-system:80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ngrok
  namespace: kube-system
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      containers:
      - image: luxas/ngrok:v2.1.18
        name: ngrok
        ports:
        - name: web
          containerPort: 4040
        args:
        - start
        - -config=/etc/ngrok/ngrok.yaml
        - traefik
        volumeMounts:
          - name: ngrok-cfg
            mountPath: /etc/ngrok/
      volumes:
      - name: ngrok-cfg
        configMap:
          name: ngrok-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: kube-system
spec:
  ports:
  - port: 80
    # Run this command in order to get the public URL for this ingress controller
    # curl -sSL $(kubectl -n kube-system get svc ngrok -o template --template "{{.spec.clusterIP}}")/api/tunnels | jq  ".tunnels[].public_url" | sed 's/"//g;/http:/d'
    targetPort: 4040
  selector:
    app: ngrok
