kind: PersistentVolume
apiVersion: v1
metadata:
  name: quickstart-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/quickstart"
